name: 🐞 Report a bug
description: File a bug/issue
labels: [bug]
title: "[BUG] <Replace this with actual title>"
body:
  - type: markdown
    attributes:
      value: |
        This issue tracker is for problems with `sign` software.

        To help us understand the issue, please fill-in as much of the following information as you can:
  - type: textarea
    attributes:
      label: Current Behavior
      description: A clear & concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear & concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Example flow
      description: If you have a minimal example flow that demonstrates the issue, share it here.
      value: |
        ```
        paste your flow here
        ```
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: Please tell us about your environment. Include any relevant information on how you are running our repository.
      value: |
        - Device: (_eg._ iPhone Xs; laptop)
        - OS: (_eg._ iOS 13.5; Fedora 32)
        - Browser: (_eg._ Safari; Firefox)
        - Version: (_eg._ 13; 73)
        - Other info: (_eg._ display resolution, ease-of-access settings)
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
