# This is a basic workflow to help you get started with Actions

name: Main

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  main:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./package.json

      - name: Install Dependencies
        run: npm install

      - name: Lint code
        if: ${{ fromJSON(steps.package.outputs.content).scripts.lint }}
        run: npm run lint

      - name: Test code
        if: ${{ fromJSON(steps.package.outputs.content).scripts.test }}
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless

      - name: Coveralls
        if: ${{ fromJSON(steps.package.outputs.content).scripts.test }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build project
        if: ${{ fromJSON(steps.package.outputs.content).scripts.build }}
        run: npm run build

      - name: Deploy 🚀
        if: ${{ fromJSON(steps.package.outputs.content).scripts.build }}
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist/ # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
